name: Build & Deploy

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build Angular & Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app with custom baseHref
        run: |
          npx ng build --configuration production --base-href="/${{ github.event.repository.name }}/"

      - name: Copy index.html to 404.html for SPA routing
        run: cp dist/web/browser/index.html dist/web/browser/404.html

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        run: echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Set image name and version tag
        run: |
          echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}" >> $GITHUB_ENV
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "VERSION_TAG=1.${COMMIT_COUNT}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION_TAG .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION_TAG

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/web/browser

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4